"""Build a deterministic ImageJ ground-truth sampling plan.

The output is a measurement template for manual per-image ImageJ/Wound Healing
plugin re-measurement. It intentionally excludes unresolved metadata rows and
keeps the sample deterministic so regenerated CSVs are reviewable in git.
"""

from __future__ import annotations

import csv
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INVENTORY = ROOT / "docs" / "validation-inventory.csv"
OUT_CSV = ROOT / "docs" / "ground-truth-sampling-plan.csv"
OUT_SUMMARY = ROOT / "docs" / "ground-truth-sampling-plan-summary.md"
MAX_PER_STRATUM = 3


def evenly_spaced(rows: list[dict[str, str]], limit: int) -> list[dict[str, str]]:
    rows = sorted(rows, key=lambda row: row["image_id"])
    if len(rows) <= limit:
        return rows
    if limit == 1:
        return [rows[len(rows) // 2]]
    idxs = sorted({round(i * (len(rows) - 1) / (limit - 1)) for i in range(limit)})
    selected = [rows[i] for i in idxs]
    # Rounding can collapse positions for tiny strata; fill deterministically.
    if len(selected) < limit:
        used = {row["image_id"] for row in selected}
        for row in rows:
            if row["image_id"] not in used:
                selected.append(row)
                used.add(row["image_id"])
            if len(selected) == limit:
                break
    return sorted(selected, key=lambda row: row["image_id"])


def sample_role(row: dict[str, str]) -> str:
    dims = f'{row["image_width_px"]}x{row["image_height_px"]}'
    if row["campaign"] == "fdi-huvec-2021":
        return "hard_case_candidate"
    if row["in_combine_set"] == "True" and dims == "1800x1800":
        return "primary_clean_crop"
    if row["in_combine_set"] == "True":
        return "primary_curated_preprocess"
    return "primary_preprocess_required"


def main() -> None:
    with INVENTORY.open("r", encoding="utf-8", newline="") as fh:
        rows = list(csv.DictReader(fh))

    resolved = [row for row in rows if row["cell_line"] != "unresolved"]
    strata: dict[tuple[str, str, str], list[dict[str, str]]] = defaultdict(list)
    for row in resolved:
        key = (row["cell_line"], row["condition"], row["time_point_h"])
        strata[key].append(row)

    selected: list[dict[str, str]] = []
    for key in sorted(strata):
        selected.extend(evenly_spaced(strata[key], MAX_PER_STRATUM))

    selected = sorted(selected, key=lambda row: (row["cell_line"], row["condition"], row["time_point_h"], row["image_id"]))

    fieldnames = [
        "sample_id",
        "image_id",
        "relative_path",
        "cell_line",
        "condition",
        "time_point_h",
        "campaign",
        "in_combine_set",
        "image_width_px",
        "image_height_px",
        "sample_role",
        "imagej_area_px2",
        "imagej_width_px",
        "imagej_wound_closure_percent",
        "rater_1",
        "rater_2",
        "measurement_status",
        "notes",
    ]

    with OUT_CSV.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        for idx, row in enumerate(selected, start=1):
            writer.writerow(
                {
                    "sample_id": f"gt-{idx:03d}",
                    "image_id": row["image_id"],
                    "relative_path": row["relative_path"],
                    "cell_line": row["cell_line"],
                    "condition": row["condition"],
                    "time_point_h": row["time_point_h"],
                    "campaign": row["campaign"],
                    "in_combine_set": row["in_combine_set"],
                    "image_width_px": row["image_width_px"],
                    "image_height_px": row["image_height_px"],
                    "sample_role": sample_role(row),
                    "imagej_area_px2": "",
                    "imagej_width_px": "",
                    "imagej_wound_closure_percent": "",
                    "rater_1": "",
                    "rater_2": "",
                    "measurement_status": "pending",
                    "notes": "",
                }
            )

    by_role: dict[str, int] = defaultdict(int)
    by_cell: dict[str, int] = defaultdict(int)
    by_condition: dict[str, int] = defaultdict(int)
    by_time: dict[str, int] = defaultdict(int)
    for row in selected:
        by_role[sample_role(row)] += 1
        by_cell[row["cell_line"]] += 1
        by_condition[row["condition"]] += 1
        by_time[row["time_point_h"]] += 1

    def table(title: str, data: dict[str, int]) -> str:
        lines = [f"## {title}", "", "| Value | n |", "|---|---:|"]
        for key, value in sorted(data.items(), key=lambda item: str(item[0])):
            lines.append(f"| {key} | {value} |")
        return "\n".join(lines)

    summary = "\n\n".join(
        [
            "# Cytomove Ground-Truth Sampling Plan — Summary",
            "**Generated by:** `scripts/build_ground_truth_sample.py`  ",
            f"**Input:** `{INVENTORY.relative_to(ROOT).as_posix()}`  ",
            f"**Output:** `{OUT_CSV.relative_to(ROOT).as_posix()}`  ",
            f"**Sampling rule:** resolved metadata only; max {MAX_PER_STRATUM} images per cell line x condition x time stratum; deterministic even spacing by image ID.",
            f"**Total selected:** {len(selected)} images",
            table("By sample role", by_role),
            table("By cell line", by_cell),
            table("By condition", by_condition),
            table("By time point", by_time),
            "## Measurement Notes\n\n- Fill `imagej_area_px2`, `imagej_width_px`, and optionally `imagej_wound_closure_percent` after ImageJ/Wound Healing plugin re-measurement.\n- Keep `measurement_status` as `pending`, `measured`, `excluded`, or `needs_review`.\n- `hard_case_candidate` rows are included for robustness awareness; they should not be the only basis for the primary Pearson r calculation.\n- Unresolved timecourse images are excluded until their handwritten labels/path metadata are manually reconciled.",
        ]
    )
    OUT_SUMMARY.write_text(summary + "\n", encoding="utf-8")

    print(f"Selected {len(selected)} images")
    print(f"Wrote {OUT_CSV.relative_to(ROOT)}")
    print(f"Wrote {OUT_SUMMARY.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
